### ISSUE TITLE
[ENH] Release on workshop

### ISSUE THREAD

**Issue by stevefan1999-personal** [GmodNET/GmodDotNet#150]
Wouldn't it be good if we can just download it on the workshop instead of manually downloading it from Github ourselves?

**Comment by luttje** [comment]
I happened to bump into this old issue only now, thanks for suggesting it!

As for your suggestion: Garry's Mod doesn't allow publishing .dll files to the workshop (and that's a good thing for security reasons).

For reference, you can see which files are allowed to be published [here on the wiki](https://wiki.facepunch.com/gmod/Workshop_Addon_Creation#folderwithaddonfiles). Since the requested enhancement isn't possible, I'll close this issue.

Thanks for suggesting anyways!
